apiVersion: v2.edp.epam.com/v1alpha1
kind: CodebaseBranch
metadata:
  name: history-excerptor-master
  labels:
    affiliatedWith: "history-excerptor"
    recreateByCleanup: "true"
spec:
  branchName: master
  codebaseName: history-excerptor
  fromCommit: ''
  release: false
  version: 0.0.1
