apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-{{ .Release.Namespace }}-scc-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.jenkins.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: jenkins-scc-role
  apiGroup: rbac.authorization.k8s.io
