apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-url-patch
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
    {{- include "jenkins-operator.metaLabels" . | nindent 4 }}
data:
  jenkins-url-patch.groovy: |-
    import jenkins.model.JenkinsLocationConfiguration

    jlc = JenkinsLocationConfiguration.get()
    jlc.setUrl("{{ include "admin-tools.jenkinsUrl" . }}")
    jlc.save()
