kind: ConfigMap
apiVersion: v1
metadata:
  name: jenkins-logging-properties
  namespace: {{ .Release.Namespace }}
  labels:
    app: jenkins
data:
  logging.properties: |
    # Jenkins logging configuration

    .level={{ .Values.jenkins.logLevel }}
    handlers=java.util.logging.ConsoleHandler
    java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$-7s %2$s %5$s%6$s%n
