apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    {{ template "admin-routes.whitelist.annotation" . }}
  labels:
    app: jenkins
  {{- include "jenkins-operator.metaLabels" . | nindent 4 }}
  name: jenkins
spec:
  host: {{ template "admin-tools.hostname" . }}
  path: /{{ .Values.jenkins.basePath }}
  port:
    targetPort: {{ .Values.jenkins.port }}
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jenkins
    weight: 100
  wildcardPolicy: None
