apiVersion: v1.edp.epam.com/v1
kind: KeycloakClient
metadata:
  name: jenkins
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: jenkins
    {{- include "jenkins-operator.metaLabels" . | nindent 4 }}
spec:
  clientId: jenkins
  public: true
  directAccess: false
  realmRoles:
    - composite: administrator
      name: jenkins-administrators
    - composite: developer
      name: jenkins-users
  audRequired: false
  secret: ''
  advancedProtocolMappers: false
  webUrl: {{ template "admin-tools.jenkinsUrl" . }}
  targetRealm: {{ template "keycloak.realm" . }}
