apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-data
  labels:
    app: jenkins
    {{- include "jenkins-operator.metaLabels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.jenkins.storage.size }}
  storageClassName: {{ .Values.global.storageClass }}
  volumeMode: Filesystem